 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_collects", type: :request do
  
  # BookCollect. As you add validations to BookCollect, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookCollect.create! valid_attributes
      get book_collects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_collect = BookCollect.create! valid_attributes
      get book_collect_url(book_collect)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_collect_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      book_collect = BookCollect.create! valid_attributes
      get edit_book_collect_url(book_collect)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookCollect" do
        expect {
          post book_collects_url, params: { book_collect: valid_attributes }
        }.to change(BookCollect, :count).by(1)
      end

      it "redirects to the created book_collect" do
        post book_collects_url, params: { book_collect: valid_attributes }
        expect(response).to redirect_to(book_collect_url(BookCollect.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookCollect" do
        expect {
          post book_collects_url, params: { book_collect: invalid_attributes }
        }.to change(BookCollect, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_collects_url, params: { book_collect: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_collect" do
        book_collect = BookCollect.create! valid_attributes
        patch book_collect_url(book_collect), params: { book_collect: new_attributes }
        book_collect.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_collect" do
        book_collect = BookCollect.create! valid_attributes
        patch book_collect_url(book_collect), params: { book_collect: new_attributes }
        book_collect.reload
        expect(response).to redirect_to(book_collect_url(book_collect))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_collect = BookCollect.create! valid_attributes
        patch book_collect_url(book_collect), params: { book_collect: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_collect" do
      book_collect = BookCollect.create! valid_attributes
      expect {
        delete book_collect_url(book_collect)
      }.to change(BookCollect, :count).by(-1)
    end

    it "redirects to the book_collects list" do
      book_collect = BookCollect.create! valid_attributes
      delete book_collect_url(book_collect)
      expect(response).to redirect_to(book_collects_url)
    end
  end
end
