 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/collectbooks", type: :request do
  
  # Collectbook. As you add validations to Collectbook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Collectbook.create! valid_attributes
      get collectbooks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      collectbook = Collectbook.create! valid_attributes
      get collectbook_url(collectbook)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_collectbook_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      collectbook = Collectbook.create! valid_attributes
      get edit_collectbook_url(collectbook)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Collectbook" do
        expect {
          post collectbooks_url, params: { collectbook: valid_attributes }
        }.to change(Collectbook, :count).by(1)
      end

      it "redirects to the created collectbook" do
        post collectbooks_url, params: { collectbook: valid_attributes }
        expect(response).to redirect_to(collectbook_url(Collectbook.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Collectbook" do
        expect {
          post collectbooks_url, params: { collectbook: invalid_attributes }
        }.to change(Collectbook, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post collectbooks_url, params: { collectbook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested collectbook" do
        collectbook = Collectbook.create! valid_attributes
        patch collectbook_url(collectbook), params: { collectbook: new_attributes }
        collectbook.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the collectbook" do
        collectbook = Collectbook.create! valid_attributes
        patch collectbook_url(collectbook), params: { collectbook: new_attributes }
        collectbook.reload
        expect(response).to redirect_to(collectbook_url(collectbook))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        collectbook = Collectbook.create! valid_attributes
        patch collectbook_url(collectbook), params: { collectbook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested collectbook" do
      collectbook = Collectbook.create! valid_attributes
      expect {
        delete collectbook_url(collectbook)
      }.to change(Collectbook, :count).by(-1)
    end

    it "redirects to the collectbooks list" do
      collectbook = Collectbook.create! valid_attributes
      delete collectbook_url(collectbook)
      expect(response).to redirect_to(collectbooks_url)
    end
  end
end
